external_components:
  # pull geiger from Github @gelidusresearch grgc1 repo
  - source: github://gelidusresearch/grgc1
    components: [ geiger ]

esphome:
  name: geiger-1
  friendly_name: geiger-1

esp8266:
  board: esp01_1m

logger:
  baud_rate: 0

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: GRGC1
    password: ""

captive_portal:

web_server:
  port: 80
  version: 2


uart:
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 38400
  data_bits: 8
  stop_bits: 1
  parity: NONE

sensor:
  - platform: geiger
    update_interval: 10s
    model: GRGC1
    id: GC1
    voltage:
      name: "Voltage"
    geiger_cpm:
      name: CPM
    geiger_cps:
      name: CPS
    geiger_dose:
      name: Dose
    geiger_sound: false
    geiger_tube: SBM20
    time_id: sntp_time


switch:
  - platform: restart
    name: Restart

time:
  - platform: sntp
    id: sntp_time